---
  # NOTE: this is necessary for the ansible_env vars
  # to be available for checking below
- name: get the facts
  setup:
    filter: "*"
  register: facts

- name: give me the facts
  debug:
    msg: "{{ facts }}"
    verbosity: 1

- name: check role path
  debug:
    msg: "{{ role_path }}"
    verbosity: 1

- name: save ansible base path variable for future use
  set_fact:
    ansible_base_path: "{{ role_path }}/../../"

- name: check base path
  debug:
    msg: "{{ ansible_base_path }}"
    verbosity: 1

- name: install gems for testing
  bundler:
    chdir: "{{ testup_deploy_dir if testup_deploy_dir != '' else omit }}"
    gem_path: "vendor/bundle"

# begin cucumber
- block:
    - name: set up cucumber
      shell: "bundle exec cucumber --init"
      args:
        chdir: "{{ testup_relative_path_to_root }}"
      when: testup_cucumber_repo == ""

    - name: make sure cucumber dir exists
      file:
        path: "{{ testup_relative_path_to_root }}{{ testup_cucumber_dir }}"
        state: directory
      when: testup_cucumber_repo != ""

    - name: get cucumber tests from repo
      git:
        repo: "{{ testup_cucumber_repo }}"
        dest: "{{ testup_relative_path_to_root }}{{ testup_cucumber_dir }}"
        version: "{{ testup_cucumber_repo_version }}"
      when: testup_cucumber_repo != ""

    - name: gitignore features directory
      blockinfile:
        block:  "{{ testup_cucumber_dir }}"
        dest: "{{ testup_relative_path_to_root }}.gitignore"
        marker: "# {mark} testup"

    - name: set variables for tests
      template:
        src: "{{ testup_cucumber_vars_template }}"
        dest: "{{ testup_relative_path_to_root }}{{ testup_cucumber_dir }}support/test_vars.rb"
        force: true

  when: testup_cucumber
# end cucumber
